### ISSUE TITLE
Template Auswahl

### ISSUE THREAD

**Issue by Babelfisch** [4t2/ce_article_list#1]
Hi netspy,
eines hab ich noch: wäre toll, wenn man eigene , unterschiedliche layouts zuweisen könnte ... ich könnts schon brauchen, was meinst Du?
lg goosie

https://www.contao-community.de/showthread.php?20899-ce_article_list-Inhaltselement-f%FCr-Artikellisten/page2&p=174671#post174671

**Comment by akroii** [comment]
+ 1

**Comment by Babelfisch** [comment]
Erledigt 57cb6f6

**Comment by akroii** [comment]
Ist die Erweiterung mit Contao 3.5.8 kompatibel?

**Comment by Babelfisch** [comment]
Ja
